application:
  deploy:
    environment: "default"
    commit_sha: ${DEPLOY_COMMIT_SHA:aaaaabbbbbcccccdddddeeeeefffffggggghhhhh}
    commit_short_sha: ${DEPLOY_COMMIT_SHORT_SHA:aaaaabbb}
    commit_title: ${DEPLOY_COMMIT_TITLE:커밋 타이틀}
    commit_timestamp: ${DEPLOY_COMMIT_TIMESTAMP:1970-01-02T00:00:00+09:00}

server:
  servlet:
    encoding:
      charset: utf-8
      force: true

# Swagger
springdoc:
  api-docs:
    path: "/docs/schema"
  swagger-ui:
    path: "/docs/swagger-ui"

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_MYSQL_HOST}/${DATABASE_MYSQL_SCHEMA:rms}?${DATABASE_MYSQL_OPTION:charset=utf8mb4,utf8&createDatabaseIfNotExist=true}
    username: ${DATABASE_MYSQL_USER}
    password: ${DATABASE_MYSQL_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_size: 100
      org:
        hibernate:
          envers:
            store_data_at_delete: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      platform: mysql
      encoding: utf-8
  test:
    database:
      replace: none
  liquibase:
    change-log: classpath:/db/changelog-master.yaml
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock
  session:
    redis:
      namespace: ${REDIS_NAMESPACE:local.v1}
    timeout: 24h
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      password: ${REDIS_PASSWORD:}
      port: ${REDIS_PORT:6379}

logging:
  level:
    liquibase: INFO
    org:
      springframework:
        transaction:
          interceptor: TRACE

decorator:
  datasource:
    p6spy:
      enable-logging: false
