spring:
  config:
    import:
      - classpath:config/common/optional-jwt.yaml
      - classpath:config/common/jpa-detail-logging.yaml
  mail:
    properties:
      mail:
        debug: true
---
application:
  deploy:
    environment: "local"
