spring:
  config:
    import:
      - classpath:config/common/jpa-detail-logging.yaml
  mail:
    properties:
      mail:
        debug: true
  session:
    redis:
      namespace: ${REDIS_NAMESPACE:local.v1}
---
application:
  deploy:
    environment: "local"
