spring:
  config:
    import:
      - classpath:config/common/test.yaml
      - classpath:config/common/optional-jwt.yaml
      - classpath:config/common/jpa-detail-logging.yaml
---
spring:
  datasource:
    url: jdbc:mysql://${DATABASE_MYSQL_HOST}/${DATABASE_MYSQL_SCHEMA:rms_test}?${DATABASE_MYSQL_OPTION:charset=utf8mb4,utf8&createDatabaseIfNotExist=true}
