spring:
  config:
    import:
      - classpath:config/common/test.yaml
      - classpath:config/common/optional-jwt.yaml
      - classpath:config/common/jpa-detail-logging.yaml
---
spring:
  jpa:
    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb?useUnicode=true&characterEncoding=UTF-8;MODE=MySQL;NON_KEYWORDS=user;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: sa
    password:
  sql:
    init:
      platform: h2
