# node 기본 구성
.node:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:${NODE_VERSION}

# Offline mirror 를 구성하여 다운로드 받을 때 네트워크를 타지 않음
.node_yarn_cache:
  extends:
    - .node
  variables:
    YARN_CACHE_DIR: .yarn-cache
    YARN_NODE_ENV: development
    FRONTEND_SRC_PATH: .
  before_script:
    - cd ${FRONTEND_SRC_PATH}
    - echo "yarn-offline-mirror \"${YARN_CACHE_DIR}\"" >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - NODE_ENV=${YARN_NODE_ENV} yarn install --frozen-lockfile --no-progress
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - ${FRONTEND_SRC_PATH}/${YARN_CACHE_DIR}/
    - key: $CI_COMMIT_REF_SLUG
      paths:
        - ${FRONTEND_SRC_PATH}/node_modules/
