application:
  deploy:
    environment: "test"

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    hibernate:
      sql: DEBUG
      type: TRACE
