include:
  - local: /.gitlab/ci/jobs/templates/gradle.gitlab-ci.yaml
  - local: /.gitlab/ci/jobs/templates/node.gitlab-ci.yaml
  - local: /.gitlab/ci/jobs/templates/docker.gitlab-ci.yaml

.build:
  stage: build
  rules:
    - if: "$TEST_DISABLED || $BUILD_DISABLED"
      when: never
    - if: "$CI_COMMIT_REF_PROTECTED"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && "$CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED"
    - if: "$CI_COMMIT_REF_NAME"
      when: manual

build_vue_app:
  extends:
    - .build
    - .node_yarn_cache
  needs: [ ]
  variables:
    NODE_ENV: "production"
    FRONTEND_SRC_PATH: view
  script:
    - yarn build
  artifacts:
    name: vue_dist
    paths:
      - src/main/resources/static/

build_boot_image:
  extends:
    - .build
    - .gradle_cache
    - .in_docker
  needs:
    - test
    - build_vue_app
  variables:
    PROPERTY_REGISTRY: "-PproxyRegistryUrl=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX} -PprojectRegistryUrl=${CI_REGISTRY_URL} -PregistryUser=${CI_REGISTRY_USER} -PregistryPassword=${CI_REGISTRY_PASSWORD} -PregistryEmail=${GITLAB_USER_EMAIL}"
    PROPERTY_BUILD: "-PbindingsDir=${CI_PROJECT_DIR}/bindings -PgradleDir=${CI_PROJECT_DIR}/.gradle-cache"
    PROPERTY_IMAGE: "-PimagePath=${CI_REGISTRY_IMAGE} -PimageBaseName=${CI_COMMIT_REF_SLUG} -PimageTag=${CI_COMMIT_SHA}"
    PROPERTY_DOCKER: "-PdockerHost=${DOCKER_HOST} -PisDockerTlsVerify=true -PdockerCertPath=${DOCKER_CERT_PATH}"
  script:
    - gradle bootBuildImage ${GRADLE_CACHE_ARGS} --publishImage ${PROPERTY_REGISTRY} ${PROPERTY_BUILD} ${PROPERTY_IMAGE} ${PROPERTY_DOCKER}
