include:
  - local: /.gitlab/ci/jobs/templates/kubernetes.gitlab-ci.yaml

.development:
  extends:
    - .setup_kubectl
  stage: review
  needs:
    - build_boot_image
  interruptible: false
  rules:
    - if: "$TEST_DISABLED || $BUILD_DISABLED || $REVIEW_DISABLED"
      when: never

deploy_development:
  extends:
    - .development
    - .setup_kubernetes_application_resource_yaml
    - .kubernetes_apply
    - .save_kubernetes_resources_to_artifacts
  variables:
    APPLICATION_URL: development.${KUBE_INGRESS_BASE_DOMAIN}
    APPLICATION_NAMESPACE: ${KUBE_NAMESPACE}
    DEPLOY_ENVIRONMENT: "development"
  environment:
    name: development
    url: https://${APPLICATION_URL}/api/
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
      allow_failure: true
