// Code generated by mockery v2.53.5. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.bellsoft.net/rms/api-core/internal/models"

	repositories "gitlab.bellsoft.net/rms/api-core/internal/repositories"
)

// MockRoomGroupRepository is an autogenerated mock type for the RoomGroupRepository type
type MockRoomGroupRepository struct {
	mock.Mock
}

type MockRoomGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomGroupRepository) EXPECT() *MockRoomGroupRepository_Expecter {
	return &MockRoomGroupRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, roomGroup
func (_m *MockRoomGroupRepository) Create(ctx context.Context, roomGroup *models.RoomGroup) (*models.RoomGroup, error) {
	ret := _m.Called(ctx, roomGroup)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.RoomGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RoomGroup) (*models.RoomGroup, error)); ok {
		return rf(ctx, roomGroup)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.RoomGroup) *models.RoomGroup); ok {
		r0 = rf(ctx, roomGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.RoomGroup) error); ok {
		r1 = rf(ctx, roomGroup)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - roomGroup *models.RoomGroup
func (_e *MockRoomGroupRepository_Expecter) Create(ctx interface{}, roomGroup interface{}) *MockRoomGroupRepository_Create_Call {
	return &MockRoomGroupRepository_Create_Call{Call: _e.mock.On("Create", ctx, roomGroup)}
}

func (_c *MockRoomGroupRepository_Create_Call) Run(run func(ctx context.Context, roomGroup *models.RoomGroup)) *MockRoomGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RoomGroup))
	})
	return _c
}

func (_c *MockRoomGroupRepository_Create_Call) Return(_a0 *models.RoomGroup, _a1 error) *MockRoomGroupRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomGroupRepository_Create_Call) RunAndReturn(run func(context.Context, *models.RoomGroup) (*models.RoomGroup, error)) *MockRoomGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoomGroupRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomGroupRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoomGroupRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoomGroupRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoomGroupRepository_Delete_Call {
	return &MockRoomGroupRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoomGroupRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockRoomGroupRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoomGroupRepository_Delete_Call) Return(_a0 error) *MockRoomGroupRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomGroupRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockRoomGroupRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function with given fields: ctx, name, excludeID
func (_m *MockRoomGroupRepository) ExistsByName(ctx context.Context, name string, excludeID *uint) (bool, error) {
	ret := _m.Called(ctx, name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint) (bool, error)); ok {
		return rf(ctx, name, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint) bool); ok {
		r0 = rf(ctx, name, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uint) error); ok {
		r1 = rf(ctx, name, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomGroupRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockRoomGroupRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - excludeID *uint
func (_e *MockRoomGroupRepository_Expecter) ExistsByName(ctx interface{}, name interface{}, excludeID interface{}) *MockRoomGroupRepository_ExistsByName_Call {
	return &MockRoomGroupRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, name, excludeID)}
}

func (_c *MockRoomGroupRepository_ExistsByName_Call) Run(run func(ctx context.Context, name string, excludeID *uint)) *MockRoomGroupRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*uint))
	})
	return _c
}

func (_c *MockRoomGroupRepository_ExistsByName_Call) Return(_a0 bool, _a1 error) *MockRoomGroupRepository_ExistsByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomGroupRepository_ExistsByName_Call) RunAndReturn(run func(context.Context, string, *uint) (bool, error)) *MockRoomGroupRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, offset, limit
func (_m *MockRoomGroupRepository) FindAll(ctx context.Context, offset int, limit int) ([]models.RoomGroup, int64, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.RoomGroup
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.RoomGroup, int64, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.RoomGroup); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRoomGroupRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRoomGroupRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockRoomGroupRepository_Expecter) FindAll(ctx interface{}, offset interface{}, limit interface{}) *MockRoomGroupRepository_FindAll_Call {
	return &MockRoomGroupRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, offset, limit)}
}

func (_c *MockRoomGroupRepository_FindAll_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockRoomGroupRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockRoomGroupRepository_FindAll_Call) Return(_a0 []models.RoomGroup, _a1 int64, _a2 error) *MockRoomGroupRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRoomGroupRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]models.RoomGroup, int64, error)) *MockRoomGroupRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllWithUsers provides a mock function with given fields: ctx, offset, limit, sort
func (_m *MockRoomGroupRepository) FindAllWithUsers(ctx context.Context, offset int, limit int, sort string) ([]models.RoomGroup, int64, error) {
	ret := _m.Called(ctx, offset, limit, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithUsers")
	}

	var r0 []models.RoomGroup
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) ([]models.RoomGroup, int64, error)); ok {
		return rf(ctx, offset, limit, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) []models.RoomGroup); ok {
		r0 = rf(ctx, offset, limit, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) int64); ok {
		r1 = rf(ctx, offset, limit, sort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = rf(ctx, offset, limit, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRoomGroupRepository_FindAllWithUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithUsers'
type MockRoomGroupRepository_FindAllWithUsers_Call struct {
	*mock.Call
}

// FindAllWithUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - sort string
func (_e *MockRoomGroupRepository_Expecter) FindAllWithUsers(ctx interface{}, offset interface{}, limit interface{}, sort interface{}) *MockRoomGroupRepository_FindAllWithUsers_Call {
	return &MockRoomGroupRepository_FindAllWithUsers_Call{Call: _e.mock.On("FindAllWithUsers", ctx, offset, limit, sort)}
}

func (_c *MockRoomGroupRepository_FindAllWithUsers_Call) Run(run func(ctx context.Context, offset int, limit int, sort string)) *MockRoomGroupRepository_FindAllWithUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockRoomGroupRepository_FindAllWithUsers_Call) Return(_a0 []models.RoomGroup, _a1 int64, _a2 error) *MockRoomGroupRepository_FindAllWithUsers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRoomGroupRepository_FindAllWithUsers_Call) RunAndReturn(run func(context.Context, int, int, string) ([]models.RoomGroup, int64, error)) *MockRoomGroupRepository_FindAllWithUsers_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoomGroupRepository) FindByID(ctx context.Context, id uint) (*models.RoomGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.RoomGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.RoomGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.RoomGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomGroupRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoomGroupRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoomGroupRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoomGroupRepository_FindByID_Call {
	return &MockRoomGroupRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoomGroupRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockRoomGroupRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoomGroupRepository_FindByID_Call) Return(_a0 *models.RoomGroup, _a1 error) *MockRoomGroupRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomGroupRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*models.RoomGroup, error)) *MockRoomGroupRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithFilteredRooms provides a mock function with given fields: ctx, id, filter
func (_m *MockRoomGroupRepository) FindByIDWithFilteredRooms(ctx context.Context, id uint, filter repositories.RoomGroupRoomFilter) (*models.RoomGroup, error) {
	ret := _m.Called(ctx, id, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithFilteredRooms")
	}

	var r0 *models.RoomGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, repositories.RoomGroupRoomFilter) (*models.RoomGroup, error)); ok {
		return rf(ctx, id, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, repositories.RoomGroupRoomFilter) *models.RoomGroup); ok {
		r0 = rf(ctx, id, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, repositories.RoomGroupRoomFilter) error); ok {
		r1 = rf(ctx, id, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomGroupRepository_FindByIDWithFilteredRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithFilteredRooms'
type MockRoomGroupRepository_FindByIDWithFilteredRooms_Call struct {
	*mock.Call
}

// FindByIDWithFilteredRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - filter repositories.RoomGroupRoomFilter
func (_e *MockRoomGroupRepository_Expecter) FindByIDWithFilteredRooms(ctx interface{}, id interface{}, filter interface{}) *MockRoomGroupRepository_FindByIDWithFilteredRooms_Call {
	return &MockRoomGroupRepository_FindByIDWithFilteredRooms_Call{Call: _e.mock.On("FindByIDWithFilteredRooms", ctx, id, filter)}
}

func (_c *MockRoomGroupRepository_FindByIDWithFilteredRooms_Call) Run(run func(ctx context.Context, id uint, filter repositories.RoomGroupRoomFilter)) *MockRoomGroupRepository_FindByIDWithFilteredRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(repositories.RoomGroupRoomFilter))
	})
	return _c
}

func (_c *MockRoomGroupRepository_FindByIDWithFilteredRooms_Call) Return(_a0 *models.RoomGroup, _a1 error) *MockRoomGroupRepository_FindByIDWithFilteredRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomGroupRepository_FindByIDWithFilteredRooms_Call) RunAndReturn(run func(context.Context, uint, repositories.RoomGroupRoomFilter) (*models.RoomGroup, error)) *MockRoomGroupRepository_FindByIDWithFilteredRooms_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithRooms provides a mock function with given fields: ctx, id, roomStatus
func (_m *MockRoomGroupRepository) FindByIDWithRooms(ctx context.Context, id uint, roomStatus *models.RoomStatus) (*models.RoomGroup, error) {
	ret := _m.Called(ctx, id, roomStatus)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithRooms")
	}

	var r0 *models.RoomGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *models.RoomStatus) (*models.RoomGroup, error)); ok {
		return rf(ctx, id, roomStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, *models.RoomStatus) *models.RoomGroup); ok {
		r0 = rf(ctx, id, roomStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, *models.RoomStatus) error); ok {
		r1 = rf(ctx, id, roomStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomGroupRepository_FindByIDWithRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithRooms'
type MockRoomGroupRepository_FindByIDWithRooms_Call struct {
	*mock.Call
}

// FindByIDWithRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - roomStatus *models.RoomStatus
func (_e *MockRoomGroupRepository_Expecter) FindByIDWithRooms(ctx interface{}, id interface{}, roomStatus interface{}) *MockRoomGroupRepository_FindByIDWithRooms_Call {
	return &MockRoomGroupRepository_FindByIDWithRooms_Call{Call: _e.mock.On("FindByIDWithRooms", ctx, id, roomStatus)}
}

func (_c *MockRoomGroupRepository_FindByIDWithRooms_Call) Run(run func(ctx context.Context, id uint, roomStatus *models.RoomStatus)) *MockRoomGroupRepository_FindByIDWithRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(*models.RoomStatus))
	})
	return _c
}

func (_c *MockRoomGroupRepository_FindByIDWithRooms_Call) Return(_a0 *models.RoomGroup, _a1 error) *MockRoomGroupRepository_FindByIDWithRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomGroupRepository_FindByIDWithRooms_Call) RunAndReturn(run func(context.Context, uint, *models.RoomStatus) (*models.RoomGroup, error)) *MockRoomGroupRepository_FindByIDWithRooms_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithUsers provides a mock function with given fields: ctx, id
func (_m *MockRoomGroupRepository) FindByIDWithUsers(ctx context.Context, id uint) (*models.RoomGroup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithUsers")
	}

	var r0 *models.RoomGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.RoomGroup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.RoomGroup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomGroupRepository_FindByIDWithUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithUsers'
type MockRoomGroupRepository_FindByIDWithUsers_Call struct {
	*mock.Call
}

// FindByIDWithUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoomGroupRepository_Expecter) FindByIDWithUsers(ctx interface{}, id interface{}) *MockRoomGroupRepository_FindByIDWithUsers_Call {
	return &MockRoomGroupRepository_FindByIDWithUsers_Call{Call: _e.mock.On("FindByIDWithUsers", ctx, id)}
}

func (_c *MockRoomGroupRepository_FindByIDWithUsers_Call) Run(run func(ctx context.Context, id uint)) *MockRoomGroupRepository_FindByIDWithUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoomGroupRepository_FindByIDWithUsers_Call) Return(_a0 *models.RoomGroup, _a1 error) *MockRoomGroupRepository_FindByIDWithUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomGroupRepository_FindByIDWithUsers_Call) RunAndReturn(run func(context.Context, uint) (*models.RoomGroup, error)) *MockRoomGroupRepository_FindByIDWithUsers_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockRoomGroupRepository) FindByName(ctx context.Context, name string) (*models.RoomGroup, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.RoomGroup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.RoomGroup, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.RoomGroup); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RoomGroup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomGroupRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockRoomGroupRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoomGroupRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockRoomGroupRepository_FindByName_Call {
	return &MockRoomGroupRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockRoomGroupRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockRoomGroupRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoomGroupRepository_FindByName_Call) Return(_a0 *models.RoomGroup, _a1 error) *MockRoomGroupRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomGroupRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*models.RoomGroup, error)) *MockRoomGroupRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, roomGroup
func (_m *MockRoomGroupRepository) Update(ctx context.Context, roomGroup *models.RoomGroup) error {
	ret := _m.Called(ctx, roomGroup)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RoomGroup) error); ok {
		r0 = rf(ctx, roomGroup)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomGroupRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoomGroupRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - roomGroup *models.RoomGroup
func (_e *MockRoomGroupRepository_Expecter) Update(ctx interface{}, roomGroup interface{}) *MockRoomGroupRepository_Update_Call {
	return &MockRoomGroupRepository_Update_Call{Call: _e.mock.On("Update", ctx, roomGroup)}
}

func (_c *MockRoomGroupRepository_Update_Call) Run(run func(ctx context.Context, roomGroup *models.RoomGroup)) *MockRoomGroupRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.RoomGroup))
	})
	return _c
}

func (_c *MockRoomGroupRepository_Update_Call) Return(_a0 error) *MockRoomGroupRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomGroupRepository_Update_Call) RunAndReturn(run func(context.Context, *models.RoomGroup) error) *MockRoomGroupRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomGroupRepository creates a new instance of MockRoomGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomGroupRepository {
	mock := &MockRoomGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
