// Code generated by mockery v2.53.5. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.bellsoft.net/rms/api-core/internal/models"

	time "time"
)

// MockLoginAttemptRepository is an autogenerated mock type for the LoginAttemptRepository type
type MockLoginAttemptRepository struct {
	mock.Mock
}

type MockLoginAttemptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginAttemptRepository) EXPECT() *MockLoginAttemptRepository_Expecter {
	return &MockLoginAttemptRepository_Expecter{mock: &_m.Mock}
}

// CleanOldAttempts provides a mock function with given fields: ctx, before
func (_m *MockLoginAttemptRepository) CleanOldAttempts(ctx context.Context, before time.Time) error {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for CleanOldAttempts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = rf(ctx, before)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginAttemptRepository_CleanOldAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanOldAttempts'
type MockLoginAttemptRepository_CleanOldAttempts_Call struct {
	*mock.Call
}

// CleanOldAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *MockLoginAttemptRepository_Expecter) CleanOldAttempts(ctx interface{}, before interface{}) *MockLoginAttemptRepository_CleanOldAttempts_Call {
	return &MockLoginAttemptRepository_CleanOldAttempts_Call{Call: _e.mock.On("CleanOldAttempts", ctx, before)}
}

func (_c *MockLoginAttemptRepository_CleanOldAttempts_Call) Run(run func(ctx context.Context, before time.Time)) *MockLoginAttemptRepository_CleanOldAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_CleanOldAttempts_Call) Return(_a0 error) *MockLoginAttemptRepository_CleanOldAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoginAttemptRepository_CleanOldAttempts_Call) RunAndReturn(run func(context.Context, time.Time) error) *MockLoginAttemptRepository_CleanOldAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// CountRecentFailedAttempts provides a mock function with given fields: ctx, username, ipAddress, since
func (_m *MockLoginAttemptRepository) CountRecentFailedAttempts(ctx context.Context, username string, ipAddress string, since time.Time) (int64, error) {
	ret := _m.Called(ctx, username, ipAddress, since)

	if len(ret) == 0 {
		panic("no return value specified for CountRecentFailedAttempts")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (int64, error)); ok {
		return rf(ctx, username, ipAddress, since)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) int64); ok {
		r0 = rf(ctx, username, ipAddress, since)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(ctx, username, ipAddress, since)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginAttemptRepository_CountRecentFailedAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountRecentFailedAttempts'
type MockLoginAttemptRepository_CountRecentFailedAttempts_Call struct {
	*mock.Call
}

// CountRecentFailedAttempts is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - ipAddress string
//   - since time.Time
func (_e *MockLoginAttemptRepository_Expecter) CountRecentFailedAttempts(ctx interface{}, username interface{}, ipAddress interface{}, since interface{}) *MockLoginAttemptRepository_CountRecentFailedAttempts_Call {
	return &MockLoginAttemptRepository_CountRecentFailedAttempts_Call{Call: _e.mock.On("CountRecentFailedAttempts", ctx, username, ipAddress, since)}
}

func (_c *MockLoginAttemptRepository_CountRecentFailedAttempts_Call) Run(run func(ctx context.Context, username string, ipAddress string, since time.Time)) *MockLoginAttemptRepository_CountRecentFailedAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_CountRecentFailedAttempts_Call) Return(_a0 int64, _a1 error) *MockLoginAttemptRepository_CountRecentFailedAttempts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginAttemptRepository_CountRecentFailedAttempts_Call) RunAndReturn(run func(context.Context, string, string, time.Time) (int64, error)) *MockLoginAttemptRepository_CountRecentFailedAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, attempt
func (_m *MockLoginAttemptRepository) Create(ctx context.Context, attempt *models.LoginAttempt) error {
	ret := _m.Called(ctx, attempt)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LoginAttempt) error); ok {
		r0 = rf(ctx, attempt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginAttemptRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLoginAttemptRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - attempt *models.LoginAttempt
func (_e *MockLoginAttemptRepository_Expecter) Create(ctx interface{}, attempt interface{}) *MockLoginAttemptRepository_Create_Call {
	return &MockLoginAttemptRepository_Create_Call{Call: _e.mock.On("Create", ctx, attempt)}
}

func (_c *MockLoginAttemptRepository_Create_Call) Run(run func(ctx context.Context, attempt *models.LoginAttempt)) *MockLoginAttemptRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LoginAttempt))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_Create_Call) Return(_a0 error) *MockLoginAttemptRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoginAttemptRepository_Create_Call) RunAndReturn(run func(context.Context, *models.LoginAttempt) error) *MockLoginAttemptRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastSuccessfulAttempt provides a mock function with given fields: ctx, username
func (_m *MockLoginAttemptRepository) GetLastSuccessfulAttempt(ctx context.Context, username string) (*models.LoginAttempt, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetLastSuccessfulAttempt")
	}

	var r0 *models.LoginAttempt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.LoginAttempt, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.LoginAttempt); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LoginAttempt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastSuccessfulAttempt'
type MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call struct {
	*mock.Call
}

// GetLastSuccessfulAttempt is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockLoginAttemptRepository_Expecter) GetLastSuccessfulAttempt(ctx interface{}, username interface{}) *MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call {
	return &MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call{Call: _e.mock.On("GetLastSuccessfulAttempt", ctx, username)}
}

func (_c *MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call) Run(run func(ctx context.Context, username string)) *MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call) Return(_a0 *models.LoginAttempt, _a1 error) *MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call) RunAndReturn(run func(context.Context, string) (*models.LoginAttempt, error)) *MockLoginAttemptRepository_GetLastSuccessfulAttempt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginAttemptRepository creates a new instance of MockLoginAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginAttemptRepository {
	mock := &MockLoginAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
