// Code generated by mockery v2.53.5. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "gitlab.bellsoft.net/rms/api-core/internal/dto"

	models "gitlab.bellsoft.net/rms/api-core/internal/models"

	time "time"
)

// MockRoomRepository is an autogenerated mock type for the RoomRepository type
type MockRoomRepository struct {
	mock.Mock
}

type MockRoomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepository) EXPECT() *MockRoomRepository_Expecter {
	return &MockRoomRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, room
func (_m *MockRoomRepository) Create(ctx context.Context, room *models.Room) (*models.Room, error) {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room) (*models.Room, error)); ok {
		return rf(ctx, room)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room) *models.Room); ok {
		r0 = rf(ctx, room)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Room) error); ok {
		r1 = rf(ctx, room)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - room *models.Room
func (_e *MockRoomRepository_Expecter) Create(ctx interface{}, room interface{}) *MockRoomRepository_Create_Call {
	return &MockRoomRepository_Create_Call{Call: _e.mock.On("Create", ctx, room)}
}

func (_c *MockRoomRepository_Create_Call) Run(run func(ctx context.Context, room *models.Room)) *MockRoomRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Room))
	})
	return _c
}

func (_c *MockRoomRepository_Create_Call) Return(_a0 *models.Room, _a1 error) *MockRoomRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Room) (*models.Room, error)) *MockRoomRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRoomRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRoomRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoomRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRoomRepository_Delete_Call {
	return &MockRoomRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRoomRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockRoomRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoomRepository_Delete_Call) Return(_a0 error) *MockRoomRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockRoomRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByNumber provides a mock function with given fields: ctx, number, excludeID
func (_m *MockRoomRepository) ExistsByNumber(ctx context.Context, number string, excludeID *uint) (bool, error) {
	ret := _m.Called(ctx, number, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByNumber")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint) (bool, error)); ok {
		return rf(ctx, number, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint) bool); ok {
		r0 = rf(ctx, number, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uint) error); ok {
		r1 = rf(ctx, number, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_ExistsByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByNumber'
type MockRoomRepository_ExistsByNumber_Call struct {
	*mock.Call
}

// ExistsByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
//   - excludeID *uint
func (_e *MockRoomRepository_Expecter) ExistsByNumber(ctx interface{}, number interface{}, excludeID interface{}) *MockRoomRepository_ExistsByNumber_Call {
	return &MockRoomRepository_ExistsByNumber_Call{Call: _e.mock.On("ExistsByNumber", ctx, number, excludeID)}
}

func (_c *MockRoomRepository_ExistsByNumber_Call) Run(run func(ctx context.Context, number string, excludeID *uint)) *MockRoomRepository_ExistsByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*uint))
	})
	return _c
}

func (_c *MockRoomRepository_ExistsByNumber_Call) Return(_a0 bool, _a1 error) *MockRoomRepository_ExistsByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_ExistsByNumber_Call) RunAndReturn(run func(context.Context, string, *uint) (bool, error)) *MockRoomRepository_ExistsByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, filter, offset, limit, sort
func (_m *MockRoomRepository) FindAll(ctx context.Context, filter dto.RoomRepositoryFilter, offset int, limit int, sort string) ([]models.Room, int64, error) {
	ret := _m.Called(ctx, filter, offset, limit, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Room
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RoomRepositoryFilter, int, int, string) ([]models.Room, int64, error)); ok {
		return rf(ctx, filter, offset, limit, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RoomRepositoryFilter, int, int, string) []models.Room); ok {
		r0 = rf(ctx, filter, offset, limit, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RoomRepositoryFilter, int, int, string) int64); ok {
		r1 = rf(ctx, filter, offset, limit, sort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.RoomRepositoryFilter, int, int, string) error); ok {
		r2 = rf(ctx, filter, offset, limit, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRoomRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockRoomRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dto.RoomRepositoryFilter
//   - offset int
//   - limit int
//   - sort string
func (_e *MockRoomRepository_Expecter) FindAll(ctx interface{}, filter interface{}, offset interface{}, limit interface{}, sort interface{}) *MockRoomRepository_FindAll_Call {
	return &MockRoomRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter, offset, limit, sort)}
}

func (_c *MockRoomRepository_FindAll_Call) Run(run func(ctx context.Context, filter dto.RoomRepositoryFilter, offset int, limit int, sort string)) *MockRoomRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.RoomRepositoryFilter), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockRoomRepository_FindAll_Call) Return(_a0 []models.Room, _a1 int64, _a2 error) *MockRoomRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRoomRepository_FindAll_Call) RunAndReturn(run func(context.Context, dto.RoomRepositoryFilter, int, int, string) ([]models.Room, int64, error)) *MockRoomRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAvailableRooms provides a mock function with given fields: ctx, startDate, endDate, excludeReservationID
func (_m *MockRoomRepository) FindAvailableRooms(ctx context.Context, startDate time.Time, endDate time.Time, excludeReservationID *uint) ([]models.Room, error) {
	ret := _m.Called(ctx, startDate, endDate, excludeReservationID)

	if len(ret) == 0 {
		panic("no return value specified for FindAvailableRooms")
	}

	var r0 []models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *uint) ([]models.Room, error)); ok {
		return rf(ctx, startDate, endDate, excludeReservationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *uint) []models.Room); ok {
		r0 = rf(ctx, startDate, endDate, excludeReservationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, *uint) error); ok {
		r1 = rf(ctx, startDate, endDate, excludeReservationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_FindAvailableRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAvailableRooms'
type MockRoomRepository_FindAvailableRooms_Call struct {
	*mock.Call
}

// FindAvailableRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
//   - excludeReservationID *uint
func (_e *MockRoomRepository_Expecter) FindAvailableRooms(ctx interface{}, startDate interface{}, endDate interface{}, excludeReservationID interface{}) *MockRoomRepository_FindAvailableRooms_Call {
	return &MockRoomRepository_FindAvailableRooms_Call{Call: _e.mock.On("FindAvailableRooms", ctx, startDate, endDate, excludeReservationID)}
}

func (_c *MockRoomRepository_FindAvailableRooms_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time, excludeReservationID *uint)) *MockRoomRepository_FindAvailableRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(*uint))
	})
	return _c
}

func (_c *MockRoomRepository_FindAvailableRooms_Call) Return(_a0 []models.Room, _a1 error) *MockRoomRepository_FindAvailableRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_FindAvailableRooms_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, *uint) ([]models.Room, error)) *MockRoomRepository_FindAvailableRooms_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockRoomRepository) FindByID(ctx context.Context, id uint) (*models.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Room); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockRoomRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoomRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockRoomRepository_FindByID_Call {
	return &MockRoomRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockRoomRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockRoomRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoomRepository_FindByID_Call) Return(_a0 *models.Room, _a1 error) *MockRoomRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*models.Room, error)) *MockRoomRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithGroup provides a mock function with given fields: ctx, id
func (_m *MockRoomRepository) FindByIDWithGroup(ctx context.Context, id uint) (*models.Room, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithGroup")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Room, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Room); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_FindByIDWithGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithGroup'
type MockRoomRepository_FindByIDWithGroup_Call struct {
	*mock.Call
}

// FindByIDWithGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockRoomRepository_Expecter) FindByIDWithGroup(ctx interface{}, id interface{}) *MockRoomRepository_FindByIDWithGroup_Call {
	return &MockRoomRepository_FindByIDWithGroup_Call{Call: _e.mock.On("FindByIDWithGroup", ctx, id)}
}

func (_c *MockRoomRepository_FindByIDWithGroup_Call) Run(run func(ctx context.Context, id uint)) *MockRoomRepository_FindByIDWithGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRoomRepository_FindByIDWithGroup_Call) Return(_a0 *models.Room, _a1 error) *MockRoomRepository_FindByIDWithGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_FindByIDWithGroup_Call) RunAndReturn(run func(context.Context, uint) (*models.Room, error)) *MockRoomRepository_FindByIDWithGroup_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNumber provides a mock function with given fields: ctx, number
func (_m *MockRoomRepository) FindByNumber(ctx context.Context, number string) (*models.Room, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for FindByNumber")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Room, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Room); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_FindByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNumber'
type MockRoomRepository_FindByNumber_Call struct {
	*mock.Call
}

// FindByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockRoomRepository_Expecter) FindByNumber(ctx interface{}, number interface{}) *MockRoomRepository_FindByNumber_Call {
	return &MockRoomRepository_FindByNumber_Call{Call: _e.mock.On("FindByNumber", ctx, number)}
}

func (_c *MockRoomRepository_FindByNumber_Call) Run(run func(ctx context.Context, number string)) *MockRoomRepository_FindByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoomRepository_FindByNumber_Call) Return(_a0 *models.Room, _a1 error) *MockRoomRepository_FindByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_FindByNumber_Call) RunAndReturn(run func(context.Context, string) (*models.Room, error)) *MockRoomRepository_FindByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStatus provides a mock function with given fields: ctx, status
func (_m *MockRoomRepository) FindByStatus(ctx context.Context, status models.RoomStatus) ([]models.Room, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.RoomStatus) ([]models.Room, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.RoomStatus) []models.Room); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.RoomStatus) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_FindByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStatus'
type MockRoomRepository_FindByStatus_Call struct {
	*mock.Call
}

// FindByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status models.RoomStatus
func (_e *MockRoomRepository_Expecter) FindByStatus(ctx interface{}, status interface{}) *MockRoomRepository_FindByStatus_Call {
	return &MockRoomRepository_FindByStatus_Call{Call: _e.mock.On("FindByStatus", ctx, status)}
}

func (_c *MockRoomRepository_FindByStatus_Call) Run(run func(ctx context.Context, status models.RoomStatus)) *MockRoomRepository_FindByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.RoomStatus))
	})
	return _c
}

func (_c *MockRoomRepository_FindByStatus_Call) Return(_a0 []models.Room, _a1 error) *MockRoomRepository_FindByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_FindByStatus_Call) RunAndReturn(run func(context.Context, models.RoomStatus) ([]models.Room, error)) *MockRoomRepository_FindByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// IsRoomAvailable provides a mock function with given fields: ctx, roomID, startDate, endDate, excludeReservationID
func (_m *MockRoomRepository) IsRoomAvailable(ctx context.Context, roomID uint, startDate time.Time, endDate time.Time, excludeReservationID *uint) (bool, error) {
	ret := _m.Called(ctx, roomID, startDate, endDate, excludeReservationID)

	if len(ret) == 0 {
		panic("no return value specified for IsRoomAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time, *uint) (bool, error)); ok {
		return rf(ctx, roomID, startDate, endDate, excludeReservationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time, *uint) bool); ok {
		r0 = rf(ctx, roomID, startDate, endDate, excludeReservationID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, time.Time, time.Time, *uint) error); ok {
		r1 = rf(ctx, roomID, startDate, endDate, excludeReservationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepository_IsRoomAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRoomAvailable'
type MockRoomRepository_IsRoomAvailable_Call struct {
	*mock.Call
}

// IsRoomAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uint
//   - startDate time.Time
//   - endDate time.Time
//   - excludeReservationID *uint
func (_e *MockRoomRepository_Expecter) IsRoomAvailable(ctx interface{}, roomID interface{}, startDate interface{}, endDate interface{}, excludeReservationID interface{}) *MockRoomRepository_IsRoomAvailable_Call {
	return &MockRoomRepository_IsRoomAvailable_Call{Call: _e.mock.On("IsRoomAvailable", ctx, roomID, startDate, endDate, excludeReservationID)}
}

func (_c *MockRoomRepository_IsRoomAvailable_Call) Run(run func(ctx context.Context, roomID uint, startDate time.Time, endDate time.Time, excludeReservationID *uint)) *MockRoomRepository_IsRoomAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(time.Time), args[3].(time.Time), args[4].(*uint))
	})
	return _c
}

func (_c *MockRoomRepository_IsRoomAvailable_Call) Return(_a0 bool, _a1 error) *MockRoomRepository_IsRoomAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepository_IsRoomAvailable_Call) RunAndReturn(run func(context.Context, uint, time.Time, time.Time, *uint) (bool, error)) *MockRoomRepository_IsRoomAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, room
func (_m *MockRoomRepository) Update(ctx context.Context, room *models.Room) error {
	ret := _m.Called(ctx, room)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Room) error); ok {
		r0 = rf(ctx, room)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRoomRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRoomRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - room *models.Room
func (_e *MockRoomRepository_Expecter) Update(ctx interface{}, room interface{}) *MockRoomRepository_Update_Call {
	return &MockRoomRepository_Update_Call{Call: _e.mock.On("Update", ctx, room)}
}

func (_c *MockRoomRepository_Update_Call) Run(run func(ctx context.Context, room *models.Room)) *MockRoomRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Room))
	})
	return _c
}

func (_c *MockRoomRepository_Update_Call) Return(_a0 error) *MockRoomRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRoomRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Room) error) *MockRoomRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomRepository creates a new instance of MockRoomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepository {
	mock := &MockRoomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
