// Code generated by mockery v2.53.5. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "gitlab.bellsoft.net/rms/api-core/internal/models"
)

// MockPaymentMethodRepository is an autogenerated mock type for the PaymentMethodRepository type
type MockPaymentMethodRepository struct {
	mock.Mock
}

type MockPaymentMethodRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentMethodRepository) EXPECT() *MockPaymentMethodRepository_Expecter {
	return &MockPaymentMethodRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, paymentMethod
func (_m *MockPaymentMethodRepository) Create(ctx context.Context, paymentMethod *models.PaymentMethod) (*models.PaymentMethod, error) {
	ret := _m.Called(ctx, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PaymentMethod) (*models.PaymentMethod, error)); ok {
		return rf(ctx, paymentMethod)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.PaymentMethod) *models.PaymentMethod); ok {
		r0 = rf(ctx, paymentMethod)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.PaymentMethod) error); ok {
		r1 = rf(ctx, paymentMethod)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentMethodRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentMethodRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod *models.PaymentMethod
func (_e *MockPaymentMethodRepository_Expecter) Create(ctx interface{}, paymentMethod interface{}) *MockPaymentMethodRepository_Create_Call {
	return &MockPaymentMethodRepository_Create_Call{Call: _e.mock.On("Create", ctx, paymentMethod)}
}

func (_c *MockPaymentMethodRepository_Create_Call) Run(run func(ctx context.Context, paymentMethod *models.PaymentMethod)) *MockPaymentMethodRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PaymentMethod))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_Create_Call) Return(_a0 *models.PaymentMethod, _a1 error) *MockPaymentMethodRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentMethodRepository_Create_Call) RunAndReturn(run func(context.Context, *models.PaymentMethod) (*models.PaymentMethod, error)) *MockPaymentMethodRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPaymentMethodRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentMethodRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPaymentMethodRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPaymentMethodRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPaymentMethodRepository_Delete_Call {
	return &MockPaymentMethodRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPaymentMethodRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockPaymentMethodRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_Delete_Call) Return(_a0 error) *MockPaymentMethodRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentMethodRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockPaymentMethodRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByName provides a mock function with given fields: ctx, name, excludeID
func (_m *MockPaymentMethodRepository) ExistsByName(ctx context.Context, name string, excludeID *uint) (bool, error) {
	ret := _m.Called(ctx, name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByName")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint) (bool, error)); ok {
		return rf(ctx, name, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *uint) bool); ok {
		r0 = rf(ctx, name, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *uint) error); ok {
		r1 = rf(ctx, name, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentMethodRepository_ExistsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByName'
type MockPaymentMethodRepository_ExistsByName_Call struct {
	*mock.Call
}

// ExistsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - excludeID *uint
func (_e *MockPaymentMethodRepository_Expecter) ExistsByName(ctx interface{}, name interface{}, excludeID interface{}) *MockPaymentMethodRepository_ExistsByName_Call {
	return &MockPaymentMethodRepository_ExistsByName_Call{Call: _e.mock.On("ExistsByName", ctx, name, excludeID)}
}

func (_c *MockPaymentMethodRepository_ExistsByName_Call) Run(run func(ctx context.Context, name string, excludeID *uint)) *MockPaymentMethodRepository_ExistsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*uint))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_ExistsByName_Call) Return(_a0 bool, _a1 error) *MockPaymentMethodRepository_ExistsByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentMethodRepository_ExistsByName_Call) RunAndReturn(run func(context.Context, string, *uint) (bool, error)) *MockPaymentMethodRepository_ExistsByName_Call {
	_c.Call.Return(run)
	return _c
}

// FindActive provides a mock function with given fields: ctx
func (_m *MockPaymentMethodRepository) FindActive(ctx context.Context) ([]models.PaymentMethod, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindActive")
	}

	var r0 []models.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.PaymentMethod, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.PaymentMethod); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentMethodRepository_FindActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActive'
type MockPaymentMethodRepository_FindActive_Call struct {
	*mock.Call
}

// FindActive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentMethodRepository_Expecter) FindActive(ctx interface{}) *MockPaymentMethodRepository_FindActive_Call {
	return &MockPaymentMethodRepository_FindActive_Call{Call: _e.mock.On("FindActive", ctx)}
}

func (_c *MockPaymentMethodRepository_FindActive_Call) Run(run func(ctx context.Context)) *MockPaymentMethodRepository_FindActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_FindActive_Call) Return(_a0 []models.PaymentMethod, _a1 error) *MockPaymentMethodRepository_FindActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentMethodRepository_FindActive_Call) RunAndReturn(run func(context.Context) ([]models.PaymentMethod, error)) *MockPaymentMethodRepository_FindActive_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, offset, limit, sort
func (_m *MockPaymentMethodRepository) FindAll(ctx context.Context, offset int, limit int, sort string) ([]models.PaymentMethod, int64, error) {
	ret := _m.Called(ctx, offset, limit, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.PaymentMethod
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) ([]models.PaymentMethod, int64, error)); ok {
		return rf(ctx, offset, limit, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string) []models.PaymentMethod); ok {
		r0 = rf(ctx, offset, limit, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string) int64); ok {
		r1 = rf(ctx, offset, limit, sort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string) error); ok {
		r2 = rf(ctx, offset, limit, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockPaymentMethodRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPaymentMethodRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
//   - sort string
func (_e *MockPaymentMethodRepository_Expecter) FindAll(ctx interface{}, offset interface{}, limit interface{}, sort interface{}) *MockPaymentMethodRepository_FindAll_Call {
	return &MockPaymentMethodRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, offset, limit, sort)}
}

func (_c *MockPaymentMethodRepository_FindAll_Call) Run(run func(ctx context.Context, offset int, limit int, sort string)) *MockPaymentMethodRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_FindAll_Call) Return(_a0 []models.PaymentMethod, _a1 int64, _a2 error) *MockPaymentMethodRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockPaymentMethodRepository_FindAll_Call) RunAndReturn(run func(context.Context, int, int, string) ([]models.PaymentMethod, int64, error)) *MockPaymentMethodRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPaymentMethodRepository) FindByID(ctx context.Context, id uint) (*models.PaymentMethod, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.PaymentMethod, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.PaymentMethod); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentMethodRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPaymentMethodRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPaymentMethodRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockPaymentMethodRepository_FindByID_Call {
	return &MockPaymentMethodRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPaymentMethodRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockPaymentMethodRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_FindByID_Call) Return(_a0 *models.PaymentMethod, _a1 error) *MockPaymentMethodRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentMethodRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*models.PaymentMethod, error)) *MockPaymentMethodRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockPaymentMethodRepository) FindByName(ctx context.Context, name string) (*models.PaymentMethod, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.PaymentMethod
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PaymentMethod, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PaymentMethod); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentMethod)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentMethodRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockPaymentMethodRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockPaymentMethodRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockPaymentMethodRepository_FindByName_Call {
	return &MockPaymentMethodRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockPaymentMethodRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockPaymentMethodRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_FindByName_Call) Return(_a0 *models.PaymentMethod, _a1 error) *MockPaymentMethodRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentMethodRepository_FindByName_Call) RunAndReturn(run func(context.Context, string) (*models.PaymentMethod, error)) *MockPaymentMethodRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// ResetAllDefaultSelects provides a mock function with given fields: ctx
func (_m *MockPaymentMethodRepository) ResetAllDefaultSelects(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetAllDefaultSelects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentMethodRepository_ResetAllDefaultSelects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetAllDefaultSelects'
type MockPaymentMethodRepository_ResetAllDefaultSelects_Call struct {
	*mock.Call
}

// ResetAllDefaultSelects is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPaymentMethodRepository_Expecter) ResetAllDefaultSelects(ctx interface{}) *MockPaymentMethodRepository_ResetAllDefaultSelects_Call {
	return &MockPaymentMethodRepository_ResetAllDefaultSelects_Call{Call: _e.mock.On("ResetAllDefaultSelects", ctx)}
}

func (_c *MockPaymentMethodRepository_ResetAllDefaultSelects_Call) Run(run func(ctx context.Context)) *MockPaymentMethodRepository_ResetAllDefaultSelects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_ResetAllDefaultSelects_Call) Return(_a0 error) *MockPaymentMethodRepository_ResetAllDefaultSelects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentMethodRepository_ResetAllDefaultSelects_Call) RunAndReturn(run func(context.Context) error) *MockPaymentMethodRepository_ResetAllDefaultSelects_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, paymentMethod
func (_m *MockPaymentMethodRepository) Update(ctx context.Context, paymentMethod *models.PaymentMethod) error {
	ret := _m.Called(ctx, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PaymentMethod) error); ok {
		r0 = rf(ctx, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentMethodRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPaymentMethodRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentMethod *models.PaymentMethod
func (_e *MockPaymentMethodRepository_Expecter) Update(ctx interface{}, paymentMethod interface{}) *MockPaymentMethodRepository_Update_Call {
	return &MockPaymentMethodRepository_Update_Call{Call: _e.mock.On("Update", ctx, paymentMethod)}
}

func (_c *MockPaymentMethodRepository_Update_Call) Run(run func(ctx context.Context, paymentMethod *models.PaymentMethod)) *MockPaymentMethodRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PaymentMethod))
	})
	return _c
}

func (_c *MockPaymentMethodRepository_Update_Call) Return(_a0 error) *MockPaymentMethodRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentMethodRepository_Update_Call) RunAndReturn(run func(context.Context, *models.PaymentMethod) error) *MockPaymentMethodRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentMethodRepository creates a new instance of MockPaymentMethodRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentMethodRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentMethodRepository {
	mock := &MockPaymentMethodRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
