// Code generated by mockery v2.53.5. DO NOT EDIT.

package repositories

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "gitlab.bellsoft.net/rms/api-core/internal/dto"

	models "gitlab.bellsoft.net/rms/api-core/internal/models"

	repositories "gitlab.bellsoft.net/rms/api-core/internal/repositories"

	time "time"
)

// MockReservationRepository is an autogenerated mock type for the ReservationRepository type
type MockReservationRepository struct {
	mock.Mock
}

type MockReservationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservationRepository) EXPECT() *MockReservationRepository_Expecter {
	return &MockReservationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, reservation
func (_m *MockReservationRepository) Create(ctx context.Context, reservation *models.Reservation) (*models.Reservation, error) {
	ret := _m.Called(ctx, reservation)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Reservation) (*models.Reservation, error)); ok {
		return rf(ctx, reservation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Reservation) *models.Reservation); ok {
		r0 = rf(ctx, reservation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Reservation) error); ok {
		r1 = rf(ctx, reservation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReservationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - reservation *models.Reservation
func (_e *MockReservationRepository_Expecter) Create(ctx interface{}, reservation interface{}) *MockReservationRepository_Create_Call {
	return &MockReservationRepository_Create_Call{Call: _e.mock.On("Create", ctx, reservation)}
}

func (_c *MockReservationRepository_Create_Call) Run(run func(ctx context.Context, reservation *models.Reservation)) *MockReservationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Reservation))
	})
	return _c
}

func (_c *MockReservationRepository_Create_Call) Return(_a0 *models.Reservation, _a1 error) *MockReservationRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Reservation) (*models.Reservation, error)) *MockReservationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockReservationRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReservationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockReservationRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockReservationRepository_Delete_Call {
	return &MockReservationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockReservationRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockReservationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockReservationRepository_Delete_Call) Return(_a0 error) *MockReservationRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockReservationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRooms provides a mock function with given fields: ctx, reservationID
func (_m *MockReservationRepository) DeleteRooms(ctx context.Context, reservationID uint) error {
	ret := _m.Called(ctx, reservationID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRooms")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, reservationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_DeleteRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRooms'
type MockReservationRepository_DeleteRooms_Call struct {
	*mock.Call
}

// DeleteRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - reservationID uint
func (_e *MockReservationRepository_Expecter) DeleteRooms(ctx interface{}, reservationID interface{}) *MockReservationRepository_DeleteRooms_Call {
	return &MockReservationRepository_DeleteRooms_Call{Call: _e.mock.On("DeleteRooms", ctx, reservationID)}
}

func (_c *MockReservationRepository_DeleteRooms_Call) Run(run func(ctx context.Context, reservationID uint)) *MockReservationRepository_DeleteRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockReservationRepository_DeleteRooms_Call) Return(_a0 error) *MockReservationRepository_DeleteRooms_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_DeleteRooms_Call) RunAndReturn(run func(context.Context, uint) error) *MockReservationRepository_DeleteRooms_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, filter, offset, limit, sort
func (_m *MockReservationRepository) FindAll(ctx context.Context, filter dto.ReservationRepositoryFilter, offset int, limit int, sort string) ([]models.Reservation, int64, error) {
	ret := _m.Called(ctx, filter, offset, limit, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Reservation
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReservationRepositoryFilter, int, int, string) ([]models.Reservation, int64, error)); ok {
		return rf(ctx, filter, offset, limit, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.ReservationRepositoryFilter, int, int, string) []models.Reservation); ok {
		r0 = rf(ctx, filter, offset, limit, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.ReservationRepositoryFilter, int, int, string) int64); ok {
		r1 = rf(ctx, filter, offset, limit, sort)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, dto.ReservationRepositoryFilter, int, int, string) error); ok {
		r2 = rf(ctx, filter, offset, limit, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockReservationRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockReservationRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter dto.ReservationRepositoryFilter
//   - offset int
//   - limit int
//   - sort string
func (_e *MockReservationRepository_Expecter) FindAll(ctx interface{}, filter interface{}, offset interface{}, limit interface{}, sort interface{}) *MockReservationRepository_FindAll_Call {
	return &MockReservationRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter, offset, limit, sort)}
}

func (_c *MockReservationRepository_FindAll_Call) Run(run func(ctx context.Context, filter dto.ReservationRepositoryFilter, offset int, limit int, sort string)) *MockReservationRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.ReservationRepositoryFilter), args[2].(int), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockReservationRepository_FindAll_Call) Return(_a0 []models.Reservation, _a1 int64, _a2 error) *MockReservationRepository_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockReservationRepository_FindAll_Call) RunAndReturn(run func(context.Context, dto.ReservationRepositoryFilter, int, int, string) ([]models.Reservation, int64, error)) *MockReservationRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockReservationRepository) FindByID(ctx context.Context, id uint) (*models.Reservation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Reservation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Reservation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockReservationRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockReservationRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockReservationRepository_FindByID_Call {
	return &MockReservationRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockReservationRepository_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockReservationRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockReservationRepository_FindByID_Call) Return(_a0 *models.Reservation, _a1 error) *MockReservationRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*models.Reservation, error)) *MockReservationRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDWithDetails provides a mock function with given fields: ctx, id
func (_m *MockReservationRepository) FindByIDWithDetails(ctx context.Context, id uint) (*models.Reservation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithDetails")
	}

	var r0 *models.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Reservation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Reservation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_FindByIDWithDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithDetails'
type MockReservationRepository_FindByIDWithDetails_Call struct {
	*mock.Call
}

// FindByIDWithDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockReservationRepository_Expecter) FindByIDWithDetails(ctx interface{}, id interface{}) *MockReservationRepository_FindByIDWithDetails_Call {
	return &MockReservationRepository_FindByIDWithDetails_Call{Call: _e.mock.On("FindByIDWithDetails", ctx, id)}
}

func (_c *MockReservationRepository_FindByIDWithDetails_Call) Run(run func(ctx context.Context, id uint)) *MockReservationRepository_FindByIDWithDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockReservationRepository_FindByIDWithDetails_Call) Return(_a0 *models.Reservation, _a1 error) *MockReservationRepository_FindByIDWithDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_FindByIDWithDetails_Call) RunAndReturn(run func(context.Context, uint) (*models.Reservation, error)) *MockReservationRepository_FindByIDWithDetails_Call {
	_c.Call.Return(run)
	return _c
}

// FindLastReservationForRoom provides a mock function with given fields: ctx, roomID
func (_m *MockReservationRepository) FindLastReservationForRoom(ctx context.Context, roomID uint) (*models.Reservation, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for FindLastReservationForRoom")
	}

	var r0 *models.Reservation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*models.Reservation, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *models.Reservation); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Reservation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_FindLastReservationForRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLastReservationForRoom'
type MockReservationRepository_FindLastReservationForRoom_Call struct {
	*mock.Call
}

// FindLastReservationForRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uint
func (_e *MockReservationRepository_Expecter) FindLastReservationForRoom(ctx interface{}, roomID interface{}) *MockReservationRepository_FindLastReservationForRoom_Call {
	return &MockReservationRepository_FindLastReservationForRoom_Call{Call: _e.mock.On("FindLastReservationForRoom", ctx, roomID)}
}

func (_c *MockReservationRepository_FindLastReservationForRoom_Call) Run(run func(ctx context.Context, roomID uint)) *MockReservationRepository_FindLastReservationForRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockReservationRepository_FindLastReservationForRoom_Call) Return(_a0 *models.Reservation, _a1 error) *MockReservationRepository_FindLastReservationForRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_FindLastReservationForRoom_Call) RunAndReturn(run func(context.Context, uint) (*models.Reservation, error)) *MockReservationRepository_FindLastReservationForRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatistics provides a mock function with given fields: ctx, startDate, endDate, periodType
func (_m *MockReservationRepository) GetStatistics(ctx context.Context, startDate time.Time, endDate time.Time, periodType string) ([]repositories.ReservationStatistics, error) {
	ret := _m.Called(ctx, startDate, endDate, periodType)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 []repositories.ReservationStatistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) ([]repositories.ReservationStatistics, error)); ok {
		return rf(ctx, startDate, endDate, periodType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, string) []repositories.ReservationStatistics); ok {
		r0 = rf(ctx, startDate, endDate, periodType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repositories.ReservationStatistics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, string) error); ok {
		r1 = rf(ctx, startDate, endDate, periodType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReservationRepository_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type MockReservationRepository_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
//   - startDate time.Time
//   - endDate time.Time
//   - periodType string
func (_e *MockReservationRepository_Expecter) GetStatistics(ctx interface{}, startDate interface{}, endDate interface{}, periodType interface{}) *MockReservationRepository_GetStatistics_Call {
	return &MockReservationRepository_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx, startDate, endDate, periodType)}
}

func (_c *MockReservationRepository_GetStatistics_Call) Run(run func(ctx context.Context, startDate time.Time, endDate time.Time, periodType string)) *MockReservationRepository_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(string))
	})
	return _c
}

func (_c *MockReservationRepository_GetStatistics_Call) Return(_a0 []repositories.ReservationStatistics, _a1 error) *MockReservationRepository_GetStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReservationRepository_GetStatistics_Call) RunAndReturn(run func(context.Context, time.Time, time.Time, string) ([]repositories.ReservationStatistics, error)) *MockReservationRepository_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, reservation
func (_m *MockReservationRepository) Update(ctx context.Context, reservation *models.Reservation) error {
	ret := _m.Called(ctx, reservation)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Reservation) error); ok {
		r0 = rf(ctx, reservation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReservationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReservationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - reservation *models.Reservation
func (_e *MockReservationRepository_Expecter) Update(ctx interface{}, reservation interface{}) *MockReservationRepository_Update_Call {
	return &MockReservationRepository_Update_Call{Call: _e.mock.On("Update", ctx, reservation)}
}

func (_c *MockReservationRepository_Update_Call) Run(run func(ctx context.Context, reservation *models.Reservation)) *MockReservationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Reservation))
	})
	return _c
}

func (_c *MockReservationRepository_Update_Call) Return(_a0 error) *MockReservationRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReservationRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Reservation) error) *MockReservationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReservationRepository creates a new instance of MockReservationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservationRepository {
	mock := &MockReservationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
